defaultSettings:
  defaultDataPath: /data/longhorn
  defaultReplicaCount: 2
  createDefaultDiskLabeledNodes: true

# Expose UI as NodePort
service:
  ui:
    type: NodePort
    nodePort: 30880

# Storage class configuration  
persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
